### ISSUE TITLE
Java source files for feeder and processor

### ISSUE THREAD

**Issue by ansyeow** [horovits/cloud-bursting#1]
Hi Dotan,

I could not find the java source files for feeder and processor. I can only find their respective jar files.

I am actually interested in learning about conflict resolution in a "master-master" scenario. (Like how will feeder/processor differentiate "replayed" mutating SQL from the ones generated by external traffic.

This project is very informative. Thanks.

Andrew

**Comment by dotanh** [comment]
Andrew,
you are perfectly right. I forgot to check in the source code. I just did that. you can find it under WAN_Gateway_example/src
there are projects for the feeder, processor and WAN gateway.
Regards,
Dotan

**Comment by ansyeow** [comment]
Hi Dotan,
Thanks. Will check them out.
Andrew
